import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { format } from 'prettier';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const rows = JSON.parse(await readFile(resolve(root, 'test', 'verification.json'), 'utf8'));
for (const row of rows) {
  if (row.live !== null && (typeof row.live !== 'string' || !/^\d{4}-\d{2}-\d{2}$/u.test(row.live))) {
    throw new TypeError(`Live verification for "${row.command}" must be an ISO date string or null.`);
  }
}
const mark = (value) => (value ? '✓' : '');
const live = (value) => (value ? `✓ ${value}` : '');

const body = rows
  .map((row) => `| \`sf ${row.command}\` | ${mark(row.unit)} | ${mark(row.mock)} | ${live(row.live)} |`)
  .join('\n');
const document = await format(
  `# Verification Matrix

Generated by \`yarn verification:generate\` from \`test/verification.json\`.

“Live verified” means that the exact CLI command completed successfully against an authorized org and has a scrubbed, schema-validated fixture with matching provenance. An empty live column means no qualifying successful public fixture exists for that command; it can also reflect an attempted-but-failed or platform-blocked run, an intentional safety gate, or an unreviewed raw trace. It does not mean unit or mocked HTTP coverage is missing.

An empty live column blocks GA verification of that command, but does not block a reviewed 0.x beta or synthetic-fixture development.

| Command | Unit | Mock NUT | Live verified |
|---|---:|---:|---|
${body}

## Excluded operations

- \`sf data360 data-space member unset\` — endpoint remains unverified (⚠); no command ships without a recorded live fixture.
- Transform pre-create validation — \`/data-transforms-validation\` remains unverified (⚠); only existing-transform validation ships.
- \`sf data360 identity-resolution publish\` — publish remains unverified (⚠); run-now is the only shipped bespoke action.
- Calculated insight \`report\`, \`validate\`, \`enable\`, and \`disable\` — action endpoints remain unverified (⚠).
- \`sf data360 segment members\` — endpoint is verified but its member payload remains opaque; command stays in backlog.
- \`sf data360 search-index report\` — process-history remains unverified (⚠).
- Data graph plain \`GET /data-graphs\` list — remains unverified (⚠); list uses the verified \`/data-graphs/metadata\` form.
- Profile child-DMO selector — exact query parameter remains unverified (⚠); profile, record, and calculated-insight variants ship.
- \`sf data360 metadata search\` — core-root endpoint remains metadata-only verification (⚠); no synthetic fixture or command ships.
- All ten Data Kit commands have successful scrubbed live evidence, including disposable create, update, delete, deploy, and undeploy workflows with cleanup verification. The current API exposes per-component deployment status rather than a deployment-job endpoint.
- Document AI configuration detail/mutations and extraction — \`docai describe\` and empty \`docai config list\` responses are recorded; detail and request payloads remain unverified.
- Data Action and Data Action Target detail/mutations — list commands ship from recorded empty responses, which do not establish detail, mutation, or signing-key payloads.
- Retriever create/update/delete and configuration mutations — only list/get/configuration-list reads have recorded fixtures.
- Semantic model detail/mutations and query — the list command ships from a recorded empty response; model CRUD and Direct semantic query remain unverified.
- Consent commands — exact core-root paths and destructive semantics remain unverified.
`,
  { parser: 'markdown', printWidth: 120 }
);
const path = resolve(root, 'VERIFICATION.md');
if (process.argv.includes('--check')) {
  if ((await readFile(path, 'utf8')) !== document) {
    throw new Error(`${path} is stale. Run yarn verification:generate.`);
  }
  process.stdout.write('Verification matrix is fresh.\n');
} else {
  await writeFile(path, document);
}
